"""WireMock-style stubs: model helpers, request matching, mappings, webhooks, pagination, formats."""

from api_tool.core.stubs.formats import (  # noqa: F401
    BODY_FORMATS,
    PAGINATED_FORMATS,
    content_type_for,
    header_value,
    format_from_content_type,
    page_to_xml,
    records_to_csv,
    render_page,
    detect_format,
)

from api_tool.core.stubs.mappings import (  # noqa: F401
    normalize_stub,
    load_mappings,
    dump_mappings,
    example_stubs,
)

from api_tool.core.stubs.matching import (  # noqa: F401
    HTTP_METHODS,
    URL_MATCH_TYPES,
    URL_MATCH_KEYS,
    VALUE_OPERATORS,
    BODY_OPERATORS,
    url_spec,
    match_value,
    match_body,
    request_matches,
    example_from_pattern,
)

from api_tool.core.stubs.model import (  # noqa: F401
    DEFAULT_PRIORITY,
    new_stub,
    new_paginated_stub,
    is_enabled,
    pagination_of,
    TEMPLATE_TRANSFORMER,
    script_of,
    is_templated,
    find_matching_stub,
    response_body_bytes,
    stub_summary,
    find_replacement_target,
    stub_tags,
)

from api_tool.core.stubs.pagination import (  # noqa: F401
    PAGINATION_MODES,
    DEFAULT_PAGE_SIZE,
    encode_cursor,
    decode_cursor,
    paginate_records,
    parse_records,
    PAGINATION_PRESETS,
    PAGE_VARIABLES,
    apply_preset,
    matching_preset,
    check_pagination,
    find_page_links,
    envelope_of,
    paginate,
    default_payload,
    link_header,
    simulated_failure,
    reset_simulated_failures,
)

from api_tool.core.stubs.webhooks import (  # noqa: F401
    new_webhook,
    webhook_delay_ms,
    webhooks_of,
    set_webhooks,
    webhook_url,
)


__all__ = [
    "BODY_FORMATS",
    "PAGINATED_FORMATS",
    "content_type_for",
    "header_value",
    "format_from_content_type",
    "page_to_xml",
    "records_to_csv",
    "render_page",
    "detect_format",
    "normalize_stub",
    "load_mappings",
    "dump_mappings",
    "example_stubs",
    "HTTP_METHODS",
    "URL_MATCH_TYPES",
    "URL_MATCH_KEYS",
    "VALUE_OPERATORS",
    "BODY_OPERATORS",
    "url_spec",
    "match_value",
    "match_body",
    "request_matches",
    "example_from_pattern",
    "DEFAULT_PRIORITY",
    "new_stub",
    "new_paginated_stub",
    "is_enabled",
    "pagination_of",
    "TEMPLATE_TRANSFORMER",
    "script_of",
    "is_templated",
    "find_matching_stub",
    "response_body_bytes",
    "stub_summary",
    "find_replacement_target",
    "stub_tags",
    "PAGINATION_MODES",
    "DEFAULT_PAGE_SIZE",
    "encode_cursor",
    "decode_cursor",
    "paginate_records",
    "parse_records",
    "PAGINATION_PRESETS",
    "PAGE_VARIABLES",
    "apply_preset",
    "matching_preset",
    "check_pagination",
    "find_page_links",
    "envelope_of",
    "paginate",
    "default_payload",
    "link_header",
    "simulated_failure",
    "reset_simulated_failures",
    "new_webhook",
    "webhook_delay_ms",
    "webhooks_of",
    "set_webhooks",
    "webhook_url",
]
